### ISSUE TITLE
Upgrade to Elm 0.17, or 0.18 once it is released

### ISSUE THREAD

**Issue by ohanhi** [ohanhi/elm-native-ui#39]
This includes forking the new compiler and core.

**Comment by prozacchiwawa** [comment]
Regarding elm 0.17, I've made a proof of concept port to elm 0.17 that uses ports instead of native code.   It's quite experimental, but does allow me to create a working app based on all the existing work in NativeUi. The result is here:

https://github.com/prozacchiwawa/elm-react-native-experiment

A fork of elm-native-ui is used:

https://github.com/prozacchiwawa/elm-native-ui

**Comment by GTDev87** [comment]
This is awesome work.  

I'm new to elm and I have been playing with your 0.17 fork.  I'm curious if you have thought/found a way for equivalent functionality to [Http.App.map](http://package.elm-lang.org/packages/elm-lang/html/latest/Html-App) for NativeUI since elm has moved away from signals.

**Comment by prozacchiwawa** [comment]
Thanks for trying it out. I added NativeUi.map to my fork and updated the example.

**Comment by GTDev87** [comment]
Haha that was fast.  Thanks a lot!

**Comment by ohanhi** [comment]
Just so you know, I think it's fantastic that you are trying to solve some of these problems!

I myself am leaning a little towards maybe waiting for 0.18 at this point, since it should bring custom program types to the table. But I am definitely interested in seeing how you are dealing with this stuff. :)

**Comment by prozacchiwawa** [comment]
Hey thanks for writing.  It's not really intended for widespread use or a
replacement for deeper work on elm.

Ultimately, I wanted to do an experiment to push ports as far as possible
without writing native code or modifying the compiler or generated code.
Clearly it'll be nicer to have program be more flexible.  Since elm
development is mostly driven by use cases, I was also hoping to contribute
a concrete example to the general ethos.

**Comment by lukewestby** [comment]
I started working on this with the 0.18 alpha, it totally works without ports and without patching compiler and core!

(Ignore the `Rn`s, I originally named everything `ReactNative`)

![screen shot 2016-10-13 at 10 39 21 pm](https://cloud.githubusercontent.com/assets/1508245/19375430/a9cce3e2-9199-11e6-90c9-47e51e32325f.png)

**Comment by ohanhi** [comment]
Woo, awesome @lukewestby! I need to try this out for myself. :)

**Comment by ohanhi** [comment]
This is now done, as of #41. :tada:
